import fs from 'node:fs';import assert from 'node:assert/strict';import {launch,baseURL} from './browser-helper.mjs';
const b=await launch();try{const p=await b.newPage({viewport:{width:450,height:800},deviceScaleFactor:1.5,isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto(`${baseURL}/?debug=0`);await p.waitForFunction(()=>window.__planet);await p.evaluate(()=>__planet.pause(true));await p.click('.environment-toggle');assert.equal(await p.locator('.environment-toggle').getAttribute('aria-expanded'),'true');
for(const [s,label] of [['spring','春天'],['summer','夏天'],['autumn','秋天'],['winter','冬天']]){await p.getByRole('button',{name:label,exact:true}).click();assert.equal(await p.evaluate(()=>__planet.view.season),s);assert.equal(await p.getByRole('button',{name:label,exact:true}).getAttribute('aria-pressed'),'true');}
await p.getByRole('button',{name:'午后',exact:true}).click();assert.equal(await p.locator('#time-output').textContent(),'14:00');assert.ok(await p.evaluate(()=>__planet.view.environmentUniforms.day.value>.99));await p.locator('#time-slider').fill('18');await p.locator('#time-slider').dispatchEvent('input');assert.equal(await p.locator('.weather span').textContent(),'18:00');assert.ok(await p.evaluate(()=>__planet.view.environmentUniforms.dusk.value>.5));await p.getByRole('button',{name:'关闭环境设置'}).click();
const before=await p.evaluate(()=>({angle:__planet.motion.angle,az:__planet.view.controls.getAzimuthalAngle(),polar:__planet.view.controls.getPolarAngle()}));
await p.mouse.move(220,370);await p.mouse.down();await p.mouse.move(430,650,{steps:14});await p.mouse.up();await p.waitForTimeout(500);const dragged=await p.evaluate(()=>({angle:__planet.motion.angle,az:__planet.view.controls.getAzimuthalAngle(),polar:__planet.view.controls.getPolarAngle()}));assert.equal(dragged.angle,before.angle);assert.ok(Math.abs(dragged.polar-before.polar)>.01);assert.ok(dragged.polar>=.86&&dragged.polar<=1.55001);assert.ok(Math.abs(Math.atan2(Math.sin(dragged.az-Math.PI),Math.cos(dragged.az-Math.PI)))<=.42001);
await p.mouse.wheel(0,-8000);await p.waitForTimeout(250);assert.ok(await p.evaluate(()=>__planet.view.camera.position.length()>=__planet.view.controls.minDistance-.001));await p.evaluate(()=>__planet.resetCamera());await p.waitForTimeout(200);assert.ok(await p.evaluate(()=>Math.abs(__planet.view.controls.getPolarAngle()-1.3)<1e-6));
const cdp=await p.context().newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:200,y:370}]});for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:200+i*16,y:370-i*7}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(400);assert.ok(await p.evaluate(()=>Math.abs(__planet.view.controls.getPolarAngle()-1.3)>.01));
const report=await p.evaluate(()=>{const a=__planet,v=a.view;for(const key of ['spring','summer','autumn','winter']){a.setSeason(key);for(const h of [0,6,12,18,24]){a.setTime(h);v.render();}}a.setSeason('spring');for(let i=0;i<24;i++)a.advance(.5);a.pause(true);const start=a.stats(),refs=[];v.scene.traverse(o=>refs.push(o));for(let i=0;i<120;i++){a.setSeason(['spring','summer','autumn','winter'][i%4]);a.setTime(i%25);v.render();}const end=a.stats(),after=[];v.scene.traverse(o=>after.push(o));return {start,end,same:refs.length===after.length&&refs.every((o,i)=>o===after[i])};});assert.ok(report.same);for(const k of ['objects','meshes','geometries','textures','programs'])assert.equal(report.start[k],report.end[k],k+' grew');assert.deepEqual(errors,[]);
report.passed=true;report.errors=errors;report.camera={before,dragged};fs.writeFileSync('artifacts/seasons/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:true,resources:report.end,camera:report.camera,errors},null,2));}finally{await b.close();}
