import {SEASONS,formatHour,environmentAt} from './planet-environment.js';
import './style.css';
import {PlanetMotion} from './planet-motion.js';
import {PlanetView} from './planet-view.js';
import {loadAssets} from './assets.js';
const params=new URLSearchParams(location.search);document.querySelector('#viewport').classList.add('planet-viewport');
const motion=new PlanetMotion(13,1.5);let view;
try{const assets=await loadAssets(['bus','bakery','cafe','florist','planet_lamp','Bench','FlowerPot_A','FlowerPot_B','planet_church','planet_windmill','planet_lighthouse','planet_umbrella']);view=new PlanetView(document.querySelector('canvas'),motion,assets);}catch(e){const el=document.querySelector('#error');el.hidden=false;el.textContent='无法启动小星球：'+e.message;throw e;}
view.renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();pause(true);const el=document.querySelector('#error');el.hidden=false;el.textContent='图形上下文已中断，请刷新页面恢复。';});
let paused=false,previous=performance.now(),frames=0;const times=new Float32Array(600);let cursor=0,count=0;
function stats(){const a=Array.from(times.subarray(0,count)).sort((a,b)=>a-b);const mean=a.reduce((s,n)=>s+n,0)/Math.max(1,a.length);return {...view.stats(),fps:mean?1000/mean:0,frameMsP95:a[Math.floor(a.length*.95)]||0,paused,frames};}
function pause(value=!paused){paused=value;const button=document.querySelector('#travel-toggle');if(button)button.textContent=paused?'继续行驶':'暂停行驶';}
const panel=document.createElement('aside');panel.className='debug-panel';panel.hidden=!params.has('debug')||params.get('debug')==='0';panel.innerHTML='<h1>小星球 · 环绕公路</h1><p class="hint">完整球面 · 固定资源 · 空格暂停</p><label class="control">行驶速度<input name="speed" type="range" min="0" max="5" step=".1" value="1.5"></label><label class="control">镜头远近<input name="zoom" type="range" min=".8" max="1.3" step=".01" value=".94"></label><button id="pause">暂停 / 继续</button> <button id="reset">重置</button><pre class="metrics"></pre>';if(params.get('debug')!=='0')document.body.append(panel);
panel.querySelector('[name=speed]').oninput=e=>motion.speed=Number(e.target.value);panel.querySelector('[name=zoom]').oninput=e=>{view.config.zoom=Number(e.target.value);view.resize();};panel.querySelector('#pause').onclick=()=>pause();panel.querySelector('#reset').onclick=()=>view.reset();addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if(e.code==='Space'){e.preventDefault();pause();}if(e.code==='KeyD')panel.hidden=!panel.hidden;});addEventListener('resize',()=>view.resize());document.addEventListener('visibilitychange',()=>previous=performance.now());
const ui=document.createElement('section');ui.className='planet-tools';ui.innerHTML=`<p class="orbit-hint">拖动调整视角 · 双指缩放</p><button class="environment-toggle" aria-expanded="false" aria-controls="environment-panel">四季 / 时间</button><div id="environment-panel" class="environment-panel" hidden><div class="environment-heading"><span>小星球的此刻</span><button class="environment-close" aria-label="关闭环境设置">×</button></div><div class="season-options" aria-label="选择季节">${Object.entries(SEASONS).map(([key,p])=>`<button data-season="${key}" aria-pressed="false">${p.label}天</button>`).join('')}</div><label class="time-control"><span>时间</span><output id="time-output">20:36</output><input aria-label="时间" id="time-slider" type="range" min="0" max="24" step="0.1" value="20.6"></label><div class="time-presets"><button data-hour="6.5">清晨</button><button data-hour="14">午后</button><button data-hour="18">黄昏</button><button data-hour="20.6">夜晚</button></div><div class="view-actions"><button id="camera-home">视角复位</button><button id="travel-toggle">暂停行驶</button></div><p class="panel-tip">左右转动约 24°，可上下倾斜与轻微缩放。</p></div>`;
document.querySelector('#viewport').append(ui);const environmentPanel=ui.querySelector('#environment-panel'),environmentToggle=ui.querySelector('.environment-toggle');function showEnvironment(open){environmentPanel.hidden=!open;environmentToggle.setAttribute('aria-expanded',String(open));}environmentToggle.onclick=()=>showEnvironment(environmentPanel.hidden);ui.querySelector('.environment-close').onclick=()=>showEnvironment(false);ui.querySelector('#camera-home').onclick=()=>view.resetCamera();ui.querySelector('#travel-toggle').onclick=()=>pause();
function setSeason(value){view.setSeason(value);for(const button of ui.querySelectorAll('[data-season]'))button.setAttribute('aria-pressed',String(button.dataset.season===view.season));}
function setTime(value){view.setTime(value);const text=formatHour(view.hour);ui.querySelector('#time-output').textContent=text;ui.querySelector('#time-slider').value=view.hour;const weather=document.querySelector('.weather');weather.querySelector('span').textContent=text;weather.setAttribute('aria-label',text);const svg=weather.querySelector('svg');svg.innerHTML=environmentAt(view.hour).day>.5?'<circle cx="14" cy="14" r="5"/><path d="M14 2v3m0 18v3M2 14h3m18 0h3M5.5 5.5l2 2m13 13 2 2M5.5 22.5l2-2m13-13 2-2"/>':'<path d="M21 18A10 10 0 0 1 10 4a10 10 0 1 0 11 14Z"/>';}
for(const button of ui.querySelectorAll('[data-season]'))button.onclick=()=>setSeason(button.dataset.season);for(const button of ui.querySelectorAll('[data-hour]'))button.onclick=()=>setTime(Number(button.dataset.hour));ui.querySelector('#time-slider').oninput=e=>setTime(Number(e.target.value));
setSeason(params.get('season')||'spring');setTime(params.has('hour')?Number(params.get('hour')):20.6);
function frame(now){const raw=Math.max(0,(now-previous)/1000);previous=now;if(!document.hidden){times[cursor++%600]=raw*1000;count=Math.min(600,count+1);const dt=Math.min(raw,.1);if(!paused){motion.update(dt);view.update(dt);}view.render();frames++;if(!panel.hidden&&frames%30===0){const s=stats();panel.querySelector('.metrics').textContent=`${s.fps.toFixed(1)} FPS · p95 ${s.frameMsP95.toFixed(1)}ms\n${s.drawCalls} Draw / ${s.triangles} Tri\n${s.objects} Objects / ${s.geometries} Geometry\n${s.textures} Textures / ${s.laps} Laps\n${s.elapsed.toFixed(1)} s`;}}requestAnimationFrame(frame);}
window.__planet={motion,view,stats,pause,setSeason,setTime,resetCamera:()=>view.resetCamera(),reset:()=>view.reset(),advance(seconds){for(let i=0;i<Math.round(seconds*60);i++){motion.update(1/60);view.update(1/60);}view.render();return stats();}};requestAnimationFrame(frame);
